get:
  operationId: query
  tags:
    - SearchTrainEngineersQuery
  responses:
    200:
      description: success
      content:
        application/json:
          schema:
            title: SearchTrainEngineersResponse
            type: array
            items:
              type: object
              title: SearchTrainEngineersResponseItem
              properties:
                id:
                  $ref: '../components.yaml#/components/schemas/EmployeeId'
                active:
                  type: boolean
              required: [id, active]
