post:
  operationId: execute
  tags:
    - CreateTrainUseCase
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          title: CreateTrainRequest
          properties:
            trainId:
              $ref: '../components.yaml#/components/schemas/TrainId'
            locomotiveId:
              $ref: '../components.yaml#/components/schemas/LocomotiveId'
          required: [ trainId, locomotiveId ]
  responses:
    204:
      description: Success
