openapi: 3.0.2
info:
  title: Network context rest api definition
  version: '1'
  description: |
    Defines the rest paths which can be used to interact with the application.
servers:
  - url: http://localhost:5173
security:
  - x-auth-token: []
paths:
  /api/network/networks/add:
    $ref: "./paths/networks_add.yaml"
  /api/network/networks/search:
    $ref: "./paths/networks_search.yaml"
  /api/network/nodes/add:
    $ref: "./paths/nodes_add.yaml"
  /api/network/nodes/search:
    $ref: "./paths/nodes_search.yaml"
  /api/network/nodes/decommission:
    $ref: "./paths/nodes_decommission.yaml"
  /api/network/nodes/rename:
    $ref: "./paths/nodes_rename.yaml"
  /api/network/nodes/reposition:
    $ref: "./paths/nodes_reposition.yaml"
  /api/network/tracks/add:
    $ref: "./paths/tracks_add.yaml"
  /api/network/tracks/decommission:
    $ref: "./paths/tracks_decommission.yaml"
  /api/network/tracks/search:
    $ref: "./paths/tracks_search.yaml"
