openapi: 3.0.2
info:
  title: Assets context rest api definition
  version: '1'
  description: |
    Defines the rest paths which can be used to interact with the application.
servers:
  - url: http://localhost:5173
security:
  - x-auth-token: []
paths:
  /api/assets/search:
    $ref: './paths/search.yaml'

  /api/assets/locomotive-models/add:
    $ref: './paths/locomotive-models_add.yaml'
  /api/assets/locomotive-models/search:
    $ref: './paths/locomotive-models_search.yaml'

  /api/assets/locomotives/add:
    $ref: './paths/locomotives_add.yaml'
  /api/assets/locomotives/decommission:
    $ref: './paths/locomotives_decommission.yaml'
  /api/assets/locomotives/search:
    $ref: './paths/locomotives_search.yaml'

  /api/assets/wagon-models/add:
    $ref: './paths/wagon-models_add.yaml'
  /api/assets/wagon-models/search:
    $ref: './paths/wagon-models_search.yaml'

  /api/assets/wagons/add:
    $ref: './paths/wagons_add.yaml'
  /api/assets/wagons/decommission:
    $ref: './paths/wagons_decommission.yaml'
  /api/assets/wagons/search:
    $ref: './paths/wagons_search.yaml'
