package be.gert.trainapp.sm.personnel._model;

public enum EmployeeRole {
	TRAIN_ENGINEER,
	TRAIN_CONDUCTOR,
	TRAIN_COOK,
	TRAIN_CREW_MEMBER,
	DIESEL_MECHANIC,
	RAILWAY_MECHANIC,
	WELDER,
	DISPATCHER,
	TRAIN_YARD_MANAGER,
	SIGNAL_MAINTAINER,
	UTILITY_CLERK,
	UNASSIGNED
}
